mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: "sakdhfopawblvfnapsidnhvpawasd"
    MYSQL_DATABASE: "gogs"
gogs:
  image: gogs/gogs
  volumes:
    - /data/docker-data/gogs:/data
  ports:
    - "11002:22"
    - "innerip:11003:3000"
  links:
    - mysql
